//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miyagi.Internals.Resources.Gfx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogBoxSkin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogBoxSkin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miyagi.Internals.Resources.Gfx.DialogBoxSkin", typeof(DialogBoxSkin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.75,0,0.125,0.25.
        /// </summary>
        internal static string UV_Button {
            get {
                return ResourceManager.GetString("UV_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5,0,0.125,0.25.
        /// </summary>
        internal static string UV_Button_MouseDown {
            get {
                return ResourceManager.GetString("UV_Button_MouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.625,0,0.125,0.25.
        /// </summary>
        internal static string UV_Button_MouseEnter {
            get {
                return ResourceManager.GetString("UV_Button_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,0.5,1.
        /// </summary>
        internal static string UV_Panel {
            get {
                return ResourceManager.GetString("UV_Panel", resourceCulture);
            }
        }
    }
}
